import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// adding the main clerk auth to the main index file
 import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: 'manageproject ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
       <html lang="en">
      <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
    
  )
}
